/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package slowkouk.okienka;

import java.util.List;
import slowkouk.models.Exam;
import slowkouk.models.Language;
import slowkouk.models.WordSet;

/*
 * JFRAME SIZES: 640 x 480
 */

/**
 *
 * @author inf106634
 */
public class ExamFrame extends javax.swing.JFrame {

    private static ExamFrame examFrame;
    private static ExamSettingsPanel settingsPanel;
    private static ExamPanel examPanel;
    private static ExamResultsPanel resultsPanel;
    
    /**
     * Creates new form Exam
     */
    public ExamFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Exam Main Frame");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel1)
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                examFrame = new ExamFrame();
                settingsPanel = new ExamSettingsPanel(examFrame);
                
                settingsPanel.setBounds(10, 35, 620, 435);
                settingsPanel.setVisible(true);
                
                examFrame.setVisible(true);
                examFrame.add(settingsPanel);
                
                
            }
            
        });
    }
    //ten run coś nawalał jak puszczałem z pozycji menu, to dodałem start
    public static void start(){
        examFrame = new ExamFrame();
        settingsPanel = new ExamSettingsPanel(examFrame);
                //Settings.setAlignmentX(10);
                //Settings.setAlignmentY(35);
                
                settingsPanel.setBounds(10, 35, 620, 435);
                settingsPanel.setVisible(true);
                
                examFrame.setVisible(true);
                examFrame.add(settingsPanel);
    
    }
    
    public static void startQuestions(Language language, WordSet set){
        //todo: przyjęcie jako parametr języka i zestawu słówek.
        Exam exam = new Exam(language, set);
        
        if(examPanel!=null)examFrame.remove(examPanel);
        examPanel = new ExamPanel(examFrame, exam);
        examPanel.setBounds(10, 35, 620, 435);
        examPanel.setVisible(true);
        //chowam poprzedni panel
        settingsPanel.setVisible(false);
        examFrame.setVisible(true);
        examFrame.add(examPanel);
        
        
    }
    
    public static void showResults(List<String> examResults){
        //todo: wyciągnięcie z quest Stringów na pytania (może być osobna metoda).
        
        //todo: podanie do results parametru z wynikami z quest
        ExamResultsPanel result = new ExamResultsPanel(examFrame, examResults);
        if(resultsPanel!=null)examFrame.remove(resultsPanel);
        resultsPanel=result;
        resultsPanel.setBounds(10, 35, 620, 435);
        resultsPanel.setVisible(true);
        //chowam poprzedni panel
        examPanel.setVisible(false);
        examFrame.setVisible(true);
        examFrame.add(resultsPanel);
        
        
    }
    
     public static void repeat(){
                
                resultsPanel.setVisible(false);
                settingsPanel.setVisible(true);
                examPanel.repeatExam();
                examFrame.setVisible(true);
                examFrame.repaint();
    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    //private javax.swing.JPanel jPanel1; <- niepotrzebn panel, ktory bedzie zastepowany Panelami Exam... .
}
